config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'restaurants#search'
  get 'restaurant' => 'restaurants#index', as: 'rests'
  get 'restaurant/:id' => 'restaurants#show', as: 'rest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant
    include ActiveModel::Model

    # indexのリクエスト
    def self.search(lat, lng, range, freeword, no_smoking, card, bottomless_cup, buffet, parking, wifi)
        uri = "https://api.gnavi.co.jp/RestSearchAPI/v3/"
        access_key = ENV['GNAVI_API_KEY']
        url = uri << "?keyid=" << access_key << "&hit_per_page=100"  << "&latitude=" << lat << "&longitude=" << lng << "&range=" << range
        # 各パラメータが送られていたらURLを上書き
        if freeword != ""
            url = url << "&freeword=" << freeword
        end

        if no_smoking != nil
            url = url << "&no_smoking=" << no_smoking
        end

        if card != nil
            url = url << "&card=" << card
        end

        if bottomless_cup != nil
            url = url << "&bottomless_cup=" << bottomless_cup
        end

        if buffet != nil
            url = url << "&buffet=" << buffet
        end

        if parking != nil
            url = url << "&parking=" << parking
        end

        if wifi != nil
            url = url << "&wifi=" << wifi
        end

        require 'open-uri'
        require 'net/http'
        require 'json'
        require 'active_support'
        require 'active_support/core_ext'

        url = URI.encode url
        re_url = URI.parse(url)
        json = Net::HTTP.get(re_url)
        hash = JSON.parse(json)
        shops = []
        # 条件に合う店の情報の取得を配列shopsに入れる
        if hash.has_key?("rest")
            hash["rest"].each do |shop|
                shops.push({
                    id: shop["id"],
                    name: shop["name"],
                    access_line: shop["access"]["line"],
                    access_station: shop["access"]["station"],
                    access_exit: shop["access"]["station_exit"],
                    access_walk: shop["access"]["walk"],
                    access_note: shop["access"]["note"],
                    category: shop["category"],
                    budget: shop["budget"],
                    image: shop["image_url"]["shop_image1"]
                })
            end
            return shops
                # エラーが返ってきた処理
        elsif hash.has_key?("error")

                if hash["error"].first["code"] == 400
                    error = "不正なパラメーターが指定されました。"
                elsif hash["error"].first["code"] == 401
                    error = "不正なアクセス（認証エラー）です。"
                elsif hash["error"].first["code"] == 404
                    error = "指定された店舗の情報が存在しません。"
                elsif hash["error"].first["code"] == 405
                    error = "不正なアクセスです。"
                elsif hash["error"].first["code"] == 429
                    error = "リクエスト可能な上限回数を超過しました。"
                elsif hash["error"].first["code"] == 500
                    error = "処理中にエラーが発生しました。"
                else
                    error = "エラーが発生しました。"
                end

                return error
        end
    end

    # showのリクエスト
    def self.show_search(id)

        # ぐるなびAPIにリクエスト
        uri = "https://api.gnavi.co.jp/RestSearchAPI/v3/"
        access_key = ENV['GNAVI_API_KEY']
        url = uri << "?keyid=" << access_key << "&id=" << id

        require 'open-uri'
        require 'net/http'
        require 'json'
        require 'active_support'
        require 'active_support/core_ext'

        url = URI.encode url
        re_url = URI.parse(url)
        json = Net::HTTP.get(re_url)
        hash = JSON.parse(json)
        only_shop = []

        # idの検索により、基本的に一つの情報が取り出される（each処理は必須）
        if hash.has_key?("rest")
            hash["rest"].each do |shop|
                only_shop.push({
                    name: shop["name"],
                    name_kana: shop["name_kana"],
                    category: shop["category"],
                    address: shop["address"],
                    image1: shop["image_url"]["shop_image1"],
                    image2: shop["image_url"]["shop_image2"],
                    pr_short: shop["pr"]["pr_short"],
                    pr_long: shop["pr"]["pr_long"],
                    opentime: shop["opentime"],
                    holiday: shop["holiday"],
                    tel: shop["tel"]
                })
                return only_shop
            end
        # エラーが返ってきた処理
        elsif hash.has_key?("error")
                if hash["error"]["code"] == "400"
                    error = "不正なパラメーターが指定されました。"
                elsif hash["error"]["code"] == "401"
                    error = "不正なアクセス（認証エラー）です。"
                elsif hash["error"]["code"] == "404"
                    error = "指定された店舗の情報が存在しません。"
                elsif hash["error"]["code"] == "405"
                    error = "不正なアクセスです。"
                elsif hash["error"]["code"] == "429"
                    error = "リクエスト可能な上限回数を超過しました。"
                elsif hash["error"]["code"] == "500"
                    error = "処理中にエラーが発生しました。"
                else
                    error = "エラーが発生しました。"
                end
                return error
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    def search

    end

    def index
        # restaurant.rbでリクエストの処理
        request = Restaurant.search(params[:lat], params[:lng], params[:radius], params[:freeword], params[:no_smoking],
                                    params[:card], params[:bottomless_cup], params[:buffet], params[:parking], params[:wifi])

        if request.is_a?(String)
            @error = request
            render :search
        else
            @shops = Kaminari.paginate_array(request).page(params[:page]).per(10)
        end


    end
    
    def show
        request = Restaurant.show_search(params[:id])

        if request.is_a?(String)
            @error = request
        else
            @shop = request
        end
        gon.address = @shop.first[:address]

    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gurunavi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class='nav navbar-nav navbar-left' >
      <%= link_to "Gurunavi", root_path ,{class: "nav-link"} %>
      </nav>
    </div>
  </header>
  <div class="main">
    <%= yield %>
  </div>
  <footer>©Gurunavi, Inc.</footer>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
    <div class="row">
    <div class="col-lg-1"></div>
        <div class="col-lg-10" id="showResult">
            <div class="total-count">
            <h1>検索結果</h1>
            </div>
            <div id="content">
            <%# 検索結果を一覧表示 %>
            <% @shops.each do |shop| %>
                <%= link_to rest_path(shop[:id]) do %>
                    <div class="row content-item">
                    <div class="col-lg-6">
                    <% if shop[:image] == "" %>
                        <image src="assets/no-image.jpg" class="image" >
                    <% else %>
                        <image src=<%= shop[:image] %> class="image" >
                    <% end %>
                    </div>
                    <div class="col-lg-6">
                        <h2><%= shop[:name] %></h2>
                        <p class="sub-item"><%= shop[:category] %></p>
                        <p class="sub-item"><%= shop[:access_line] %><%= shop[:access_station] %> <%=shop[:access_walk] %>分 <%=shop[:access_note] %></p>
                        <% if shop[:budget] != "" %>
                            <p class="sub-item">平均予算：<%= shop[:budget] %>円</p>
                        <% end %>
                    </div>
                    </div>
                <% end %>
            <% end %>
            <%= paginate @shops %>
            </div>
        </div>
    </div>
    <div class="col-lg-1"></div>
</div>

app/views/restaurants/search.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
        <div class="row">
        <% if @error %>
            <h2 class="error"><%= @error %></h2>
        <% end %>
            <h1>検索条件入力</h1>

            <p id="result"></p>

            <%= form_tag(rests_path, :method => 'get') do %>
                <%= text_field_tag :freeword, "", class: "col-lg-12" %>

                <%= check_box_tag :no_smoking  %>
                <%= label_tag :no_smoking, "禁煙席あり" %>

                <%= check_box_tag :card  %>
                <%= label_tag :card, "カード利用可" %>

                <%= check_box_tag :bottomless_cup  %>
                <%= label_tag :bottomless_cup, "飲み放題あり" %>

                <%= check_box_tag :buffet  %>
                <%= label_tag :buffet, "食べ放題あり" %>

                <%= check_box_tag :parking  %>
                <%= label_tag :parking, "駐車場あり" %>

                <%= check_box_tag :wifi  %>
                <%= label_tag :wifi, "wifiあり" %>

                <div class="kensaku">
                    <p>検索範囲の半径を選択してください。<%= select_tag(:radius, options_for_select([["300m","1"], ["500m", "2"], ["1000m","3"], ["2000m","4"], ["3000m","5"]], :selected => "2"), class: "select") %></p>
                </div>

                <%= submit_tag '検索する', class: "btn btn-primary col-lg-12" %>
            <% end %>
        </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
</div>



<div id="map-canvas" style="height:600px;　width:600px"></div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>"></script>
<%= javascript_include_tag "search.js" %>

app/views/restaurants/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="showcontent col-lg-10">

            <% @shop.each do |s| %>
                <div class="main-content">
                    <p><span class="category">業態</span><%= s[:category] %></p>
                    <h1><%= s[:name] %></h1>
                    <p class="name-kana"><%= s[:name_kana] %></p>
                    <h3><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span><%= s[:tel] %></h3>
                    <p>営業時間：<%= s[:opentime] %></p>
                    <p>休業日：<%= s[:holiday] %></p>
                    <p>住所：<%= s[:address] %></p>
                </div>
                <div class="sub-content">
                    <p class="pr_short"><%= s[:pr_short] %></p>
                    <p class="pr_long"><%= s[:pr_long] %></p>
                    <image src=<%= s[:image1] %> >
                    <image src=<%= s[:image2] %> >
                </div>
            <% end %>
        <div id="map-canvas" style="height:600px;　width:600px"></div>

        </div>
        <div class="col-lg-1"></div>

    </div>
</div>

<script async defer src="//maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=showMap"></script>
<%= javascript_include_tag "show.js" %>